Bad 214 oapen onix unittest table updates
The-Academic-Observatory/oaebu-workflows pull request #102
Opened 2022-07-25 08:29 UTC by keegansmith21

Removed dependency on the observatory-unit-testing project for the oapen workflow unit test and created mock data to replace the previously used real data. The test also no longer queries data from the academic-observatory dataset.

2022-07-27 02:03 UTC, jdddog requested changes
Thanks Keegan, it's much better using the mocked data now.

I just realised that there are three additional external tables in, which should also be mocked as well, the sql templates and the tables that they are used in are:
- export_book_subject_thema_metrics.jinja2
  - oaebu-public-data.oaebu_reference.thema_lookup
- export_book_subject_bic_metrics.jinja2
  - oaebu-public-data.oaebu_reference.bic_lookup
- export_book_subject_bisac_metrics.jinja2
  - oaebu-public-data.oaebu_reference.bisac_lookup

The above three tables are quite simple, should just be able to export them as CSV or JSON Lines from BigQuery, save to Git LFS and load them like you did the others.

The unit tests that checks the table content could be more thorough (I know you didn't write them!) Some ideas:
* Check that each table exists with `self.assert_table_integrity`. All of the export tables, onix and book_product tables.
* Then for the onix and book_product table, make a JSON lines file with their expected output, read it in and compare it to the actual output. You can use the `self.assert_table_content` test for this.

2022-08-01 04:53 UTC, keegansmith21 commented
Currently blocked by The-Academic-Observatory/observatory-platform#575

2022-08-03 04:50 UTC, jdddog requested changes
Thanks Keegan, that's looking good, just a few small comments.

2022-08-03 04:50 UTC, jdddog commented on oaebu_workflows/workflows/tests/test_oapen_workflow.py
> +            )
It would be good to put the tests below each task that they related to. So asserting the ONIX table content should go below `create_onix_formatted_metadata_output_tasks`, then the book product table content check below `create_oaebu_book_product_table` and the export table checks after the export tables are created. Perhaps also add the expected number of rows to `assert_table_integrity`.

You could also remove the "Check records in book_product and book_product_list match" tests by adding the expected number of rows to `assert_table_integrity` where the export tables are checked.

2022-08-08 07:09 UTC, keegansmith21 commented on oaebu_workflows/workflows/tests/test_oapen_workflow.py
> +            )
Thanks Jamie. I've made some updates and it's ready for a re-review.

2022-08-09 21:16 UTC, jdddog approved these changes
Thanks Keegan, the changes look great.

2022-08-09 21:17 UTC, merged