Bad 210 wp2 standardised data ingest pipelines workflows
The-Academic-Observatory/oaebu-workflows pull request #105
Opened 2022-08-19 06:39 UTC by keegansmith21

Integrated Crossref events and metadata into the Onix workflow to eliminate the dependency on The Academic Observatory repository.

2022-09-02 04:25 UTC, jdddog requested changes
Hey Keegan, it's looking good, I just have a few comments and questions (below). Have you run it end to end, locally for a partner?

2022-09-02 04:25 UTC, jdddog commented on oaebu_workflows/workflows/tests/test_onix_workflow.py
> +                with events_vcr.use_cassette(self.events_cassette):
You should just be able to write:
```python
with vcr.use_cassette(self.events_cassette, record_mode="none", before_record_request=vcr_ignore_condition):
```

You would use vcr.VCR when you wanted to use the same settings with many different vcr.use_cassette calls.

2022-09-02 04:25 UTC, jdddog commented on oaebu_workflows/workflows/onix_workflow.py
> +    )
These can all be moved out of the `OnixWorkflow` class and just be constants in this module.

What if there are more than 1000 rows?

2022-09-02 07:58 UTC, keegansmith21 commented on oaebu_workflows/workflows/onix_workflow.py
> +    )
The 1000 rows is a limit enforced by the API. For the events we use a cursor to iterate through pages of events. I purposely neglected to do this with the metadata as I did not expect it to be possible to have over 1000 DOIs for a single ISBN. After chatting with Cameron it appears that this is a possibility, so I'll build it into the workflow.

2022-09-05 04:22 UTC, keegansmith21 commented
@jdddog  - Comments have been addressed and ready for re-review

2022-09-07 23:51 UTC, jdddog approved these changes
Thanks Keegan, the changes look good.

2022-09-08 00:50 UTC, merged