BAD-276: Fulcrum Telescope Development
The-Academic-Observatory/oaebu-workflows pull request #113
Opened 2022-09-07 08:23 UTC by keegansmith21

Begun development for fulcrum telescope.
Much more work to do still.

2023-03-30 22:14 UTC, jdddog requested changes
Thanks Keegan, the documentation and code looks good. Just a small suggestion for now and some comments for when you update it on the new config file branch.

2023-03-30 22:14 UTC, jdddog commented on oaebu_workflows/workflows/fulcrum_telescope.py
> +}
When you update this on the new config file branch, it would be good if this org name to publisher mapping was supplied via an argument in kwargs, then the mapping can be configured without needing to change the code.

2023-03-30 22:14 UTC, jdddog commented on oaebu_workflows/workflows/fulcrum_telescope.py
> +        load_bigquery_table_kwargs={"ignore_unknown_values": True},
Default keyword arguments of type dictionary or list set in this way are mutable, meaning that they can be changed. The implication of this is that if you modified this dictionary somewhere in your code, and this constructor (or function) was called again, the `load_bigquery_table_kwargs` would be set to the same object that you modified, not the value `{"ignore_unknown_values": True}`. 

So you have to jump through some hoops in Python to make this work properly. You need to set `load_bigquery_table_kwargs: Dict = None` and then if this is set to None, you assign the value `{"ignore_unknown_values": True}`. The effect is that when the user hasn't set a value for `load_bigquery_table_kwargs` the default value that you want will be used, and if they have set a value, then what they have set will be used.

2023-03-30 22:14 UTC, jdddog commented on oaebu_workflows/workflows/fulcrum_telescope.py
> +        list_to_jsonl_gz(country_path, country_data)
In the updated branch, these have changed to save_jsonl_gz: https://github.com/The-Academic-Observatory/observatory-platform/blob/feature/workflow-config-file/observatory-platform/observatory/platform/files.py#L219

2023-03-31 01:21 UTC, keegansmith21 commented on oaebu_workflows/workflows/fulcrum_telescope.py
> +        load_bigquery_table_kwargs={"ignore_unknown_values": True},
Ahhh, I remember hearing about this once but not understanding. Thank you for the explanation, I'll update this. I still find it strange that Python behaves this way for lists/dicts.

2023-03-31 01:21 UTC, keegansmith21 commented on oaebu_workflows/workflows/fulcrum_telescope.py
> +}
Yeah I agree that would be much nicer. I'll make the change in the upcoming branch

2023-03-31 01:24 UTC, keegansmith21 commented on oaebu_workflows/workflows/fulcrum_telescope.py
> +        list_to_jsonl_gz(country_path, country_data)
Yea I'll have to do an overhaul for the upcoming changes

2023-03-31 04:46 UTC, jdddog approved these changes
Thanks Keegan, the changes look good.

2023-03-31 04:46 UTC, merged