Bad 257 oapen onix workflow
The-Academic-Observatory/oaebu-workflows pull request #118
Opened 2022-11-25 08:44 UTC by keegansmith21

This is a PR for integrating OAPEN's metadata into the onix telescope and onix workflow

2022-12-09 02:55 UTC, jdddog requested changes
Thanks for the PR Keegan, it looks good, just some comments about keeping the previous name of the telescope so that we don't have to make too many changes when deploying it and making the sensors for the ONIX Telescope able to be specified via a parameter in the constructor.

2022-12-09 02:55 UTC, jdddog commented on oaebu_workflows/workflows/oapen_metadata_workflow.py
> +    return (line_number - negative_offset, line_number + positive_offset)
I'm not sure how feasible this is, so just disregard it if it seems like too much work.

It would be cleaner if you could use the internals of `validate_onix` as it traverses the XML with the library it uses, e.g. lxml, and then use the same library to delete the invalid elements, write the valid XML out to file and create a new XML tree, add the invalid products and write them to a file. Maybe `validate_onix` isn't design to make a task like this easy though.

2022-12-09 02:55 UTC, jdddog commented on oaebu_workflows/workflows/oapen_metadata_workflow.py
> +    def __init__(
I think it would be easier to keep this named as the Oapen Metadata Telescope, as it kind of is that, we are just changing what format the data is output in and where it is saved, then we don't need to make any changes to anything related to seeding apart from removing the oapen_workflow and don't need to update the production database, aside from deleting things related to oapen_workflow.

2022-12-09 02:55 UTC, jdddog commented on oaebu_workflows/workflows/onix_telescope.py
> +        if self.organisation_name == "OAPEN Press":
It would be better to not add a hard coded sensor into the OnixTelescope. Instead, you could use the pattern below:

```python
class MyWorkflow(Workflow):
    def __init__(
        self,
        *,
        sensor_dag_ids: List[str] = None,
        ...
    ):
        ...
        self.sensor_dag_ids = sensor_dag_ids
        if sensor_dag_ids is None:
            self.sensor_dag_ids = []

        # Add a list of ExternalTask sensors to wait for other DAGs to finish
        for dag_id in self.sensor_dag_ids:
            self.add_sensor(
                ExternalTaskSensor(
                    task_id=f"{dag_id}_sensor",
                    external_dag_id=dag_id,
                    mode="reschedule",
                )
            )

```

You would need to store the sensor_dag_ids in the extras field of the workflow in the API, as a JSON list, then in dags/onix_workflow.py you would need to grab the list of sensor_dag_ids from the API with workflow.extras.get("sensor_dag_ids") and parse the JSON list.

2022-12-09 02:58 UTC, keegansmith21 commented on oaebu_workflows/workflows/onix_workflow.py
> +    return isbns[:200]
Good pickup, I was meant to change this back post-test

2022-12-09 04:00 UTC, keegansmith21 commented on oaebu_workflows/workflows/oapen_metadata_workflow.py
> +    return (line_number - negative_offset, line_number + positive_offset)
Yeah I'm aware that this is a pretty subpar solution. It turns out handling XML files is just kinda hard.

I didn't look into doing what you suggest here when writing this, but I've had a play around now and I think it's probably more trouble than its worth. The onixcheck library mostly just wraps the lmxl library and adds a few schemas to validate against that conform to ONIX standards. The lxml library is great for validating, but the issue is that it can't do it iteratively as far as I can see. It also doesn't have any way to store/return the xml elements that contain the invalid components; it can only tell you the line in which the error occurs. I think this is closer to a limitation of the xml format than with the library itself though, since it'd have no way of knowing that you are specifically looking for the second-to top level element that contains each error.

2022-12-09 04:01 UTC, keegansmith21 commented on oaebu_workflows/workflows/oapen_metadata_workflow.py
> +    def __init__(
Damn, wish I'd known this before changing everything! haha

But no problem. I only called it a workflow because it's removing a few things about the data it's gathering.

2022-12-14 03:09 UTC, jdddog commented on oaebu_workflows/workflows/oapen_metadata_workflow.py
> +    return (line_number - negative_offset, line_number + positive_offset)
No worries!

2022-12-14 05:32 UTC, jdddog submitted a review, later dismissed
Thanks Keegan, the changes look good.

2022-12-15 02:53 UTC, jdddog approved these changes

2022-12-15 20:38 UTC, merged