BAD-372: Thoth Telescope
The-Academic-Observatory/oaebu-workflows pull request #119
Opened 2022-11-25 08:45 UTC by keegansmith21

This is a PR for the creation of the Thoth telescope into OAEBU workflows

2023-01-10 08:04 UTC, keegansmith21 commented
@jdddog just a question about the design that would be good to have your input on when you're ready to review:
This currently works as a standalone telescope in that it'll pull data from Thoth, transform it and create a BQ table. There is another option for the telescope design that I did not consider until after creating it... We could make the workflow follow a similar pattern as with the OAPEN metadata telescope (#118). That is to say, we could download the onix XML (from Thoth) and upload it to the SFTP server's upload file. Then we could simply let the ONIX telescope pick up the file and process it as normal. This would have the advantage of confining the entirety of ONIX processing to a single telescope type. Please let me know what you think :smiley:

2023-01-13 00:33 UTC, jdddog requested changes
Hey Keegan, the workflow looks good, it is much easier to understand having less inheritance. 

> This currently works as a standalone telescope in that it'll pull data from Thoth, transform it and create a BQ table. There is another option for the telescope design that I did not consider until after creating it... We could make the workflow follow a similar pattern as with the OAPEN metadata telescope (#118).

I prefer how you have made the workflow here, because it is a more straightforward way to get the data into BigQuery.

The main changes suggested are:
* `publisher_id` can be a parameter passed to the workflow and stored in the extra field of the workflow in the API.
* It would be good to remove `organisation_name`. It is inconsistent that this parameter
is used to create the `dataset_description` inside the workflow, and the `dag_id` from outside the workflow
in the dag file. I think it would be cleaner to remove it
entirely and set both the `dag_id` and `dataset_description` in the dag file. We can remove the need for the organisation name for `parse_onix`.
* By having a separate variable for the `workflow_folder`, we can make the cleanup simpler, and also put the cleanup functionality into a function.

2023-01-13 00:33 UTC, jdddog commented on oaebu_workflows/workflows/thoth_telescope.py
> +        self.transform_folder = make_workflow_folder(self.dag_id, release_date, SubFolder.transformed.value)
I would modify this a little bit, so that the folder created by `get_data_path(), dag_id, f"{dag_id}_{release_string}"` can be accessed separately, e.g. as self.workflow_folder.

Perhaps then `make_workflow_folder` could just create the path at `workflow_folder` and you can make the download_folder and transform_folder after this with os.path.join.

This is so that you can use `self.workflow_folder` to cleanup the whole workflow folder.

2023-01-13 00:33 UTC, jdddog commented on oaebu_workflows/workflows/thoth_telescope.py
> +        :raises AirflowException: Raised if there is not exactly 1 file in the donwload folder matching the expected name
Add the remainder of the docstrings.

2023-01-13 00:33 UTC, jdddog commented on oaebu_workflows/workflows/thoth_telescope.py
> +        """Task to download the ONIX release from Thoth."""
Add the remainder of the docstrings.

2023-01-13 00:33 UTC, jdddog commented on oaebu_workflows/workflows/thoth_telescope.py
> +        )
```suggestion
        thoth_download_onix(
            host_name=self.host_name,
            publisher_id=self.publisher_id,
            download_folder=self.download_folder,
            format_spec=self.format_specification,
        )
```

2023-01-13 00:33 UTC, jdddog commented on oaebu_workflows/workflows/thoth_telescope.py
> +        parse_onix(self.download_folder, self.transform_folder, make_org_id(self.organisation_name))
The source variable of `parse_onix` is used to create a field called `COKI_ID`, which we don't use anywhere. We can remove the need for `make_org_id(self.organisation_name)` by removing this from the ONIX Parser.

These are the lines to remove in ONIX Parser, along with the associated `data_src` variables:
https://github.com/The-Academic-Observatory/onix-parser/blob/main/src/main/java/academy/observatory/app/OnixParser.java#L208-L209

2023-01-13 00:33 UTC, jdddog commented on oaebu_workflows/workflows/thoth_telescope.py
> +        """Upload the downloaded thoth onix .jsonl to google cloud bucket"""
Add remaining docstrings.

2023-01-13 00:33 UTC, jdddog commented on oaebu_workflows/workflows/thoth_telescope.py
> +                logging.warning(f"No such file or directory {path}: {e}")
It would be useful to move the cleanup functionality into a reusable function, as this will be reused across workflows, see below for function. Typically the cleanup should remove the workflow folder and also remove any XComs.

```suggestion
        """Delete all files and folders associated with this release."""
        
        cleanup(self.workflow_folder, self.dag_id, kwargs["execution_date"])
```

2023-01-13 00:33 UTC, jdddog commented on oaebu_workflows/workflows/thoth_telescope.py
> +
We can remove the entire workflow_folder rather than each subfolder.

```suggestion
def cleanup(workflow_folder, dag_id: str, execution_date):
    # Cleanup workflow folder
    try:
        shutil.rmtree(workflow_folder)
    except FileNotFoundError as e:
        logging.warning(f"No such file or directory {workflow_folder}: {e}")

    # Cleanup XComs
    delete_old_xcoms(dag_id=dag_id, execution_date=execution_date)
```

2023-01-13 00:33 UTC, jdddog commented on oaebu_workflows/workflows/thoth_telescope.py
> +    publisher_id: str,
If hostname can be altered, then better to let it be specified with an argument.

```suggestion
    *,
    host_name: str,
```

2023-01-13 00:33 UTC, jdddog commented on oaebu_workflows/workflows/thoth_telescope.py
> +
```suggestion

    :param host_name: the Thoth hostname.
```

2023-01-13 00:33 UTC, jdddog commented on oaebu_workflows/workflows/thoth_telescope.py
> +    )
```suggestion
    url = THOTH_URL.format(host_name=host_name, format_specification=format_spec, publisher_id=publisher_id)
```

2023-01-13 00:33 UTC, jdddog commented on oaebu_workflows/workflows/thoth_telescope.py
> +    if not os.path.exists(path):
I probably put this line before `if not os.path.exists(path):` but it is not necessary.

```suggestion
```

2023-01-13 02:56 UTC, keegansmith21 commented on oaebu_workflows/workflows/thoth_telescope.py
> +        self.transform_folder = make_workflow_folder(self.dag_id, release_date, SubFolder.transformed.value)
What would you think of the following as a solution?:
```suggestion
def make_workflow_folder(dag_id: str, release_date: pendulum.DateTime, *subdirs: str) -> str:
    release_string = release_date.format("YYYY_MM_DD")
    path = os.path.join(get_data_path(), dag_id, f"{dag_id}_{release_string}", *subdirs)
    os.makedirs(path, exist_ok=True)
    return path
```

2023-01-13 03:35 UTC, keegansmith21 commented on oaebu_workflows/workflows/thoth_telescope.py
> +        parse_onix(self.download_folder, self.transform_folder, make_org_id(self.organisation_name))
Sure! I've create a [PR](https://github.com/The-Academic-Observatory/onix-parser/pull/7) for the ONIX Parser

2023-01-13 06:42 UTC, jdddog commented on oaebu_workflows/workflows/thoth_telescope.py
> +        self.transform_folder = make_workflow_folder(self.dag_id, release_date, SubFolder.transformed.value)
Yeah that looks good

2023-01-16 05:37 UTC, keegansmith21 commented
@jdddog I've implemented the changes you've requested. Apart from those, I also made these changes:

- Added test for the parse_onix() function in the onix_telescope
- Removed date_format from onix_telescope and API seed as it does not appear to be used anywhere

2023-02-03 03:46 UTC, jdddog approved these changes
Hey Keegan, the changes look really good!

2023-02-03 04:13 UTC, merged