Added alternative onix source to onix workflow
The-Academic-Observatory/oaebu-workflows pull request #128
Opened 2023-02-10 02:02 UTC by keegansmith21

2023-02-14 01:18 UTC, jdddog requested changes
Hey Keegan, I think a cleaner approach would be to make the ONIX datasets a data partner and to change the table name output by the Thoth telescope to "onix" so that there are less differences.

We should make it easier to specify data partners when we move to a config file.

2023-02-15 02:19 UTC, keegansmith21 commented
Hi @jdddog, I've addressed your comments. Adding ONIX as a data partner to the API is a very clean solution. The only thing that needed attention was two portions of the ONIX workflow. These are the parts that create the intermediate and QA tables. It doesn't make sense for ONIX to have these tables, so they are explicitly excluded.

2023-02-17 00:32 UTC, jdddog reviewed
Hey Keegan, the changes look good, just a small comment.

2023-02-17 00:32 UTC, jdddog commented on oaebu_workflows/workflows/onix_workflow.py
> +        partner_data_dag_prefix_ids = list(set([partner.dag_id_prefix for partner in data_partners]))
Since the ONIX dataset is mandatory, maybe we should make an assertion to make sure that there is one here and raise an AirflowException if not? (To catch out when we don't configure it)

2023-02-17 08:24 UTC, keegansmith21 commented
Thanks @jdddog. I've addressed your comment, which took a bit more effort than I expected for such a simple change. All of the difficulty of it was updating the tests to work by adding an ONIX dataset/workflow to the mock API. I've tried my best to keep it as clean as possible, as the onix workflow is quite extensive.

2023-02-22 02:06 UTC, jdddog approved these changes
Thanks Keegan, the changes look good!

2023-02-22 02:07 UTC, merged