Transfer changes from original telescope documentation branch
The-Academic-Observatory/oaebu-workflows pull request #13
Opened 2021-09-03 01:28 UTC by aroelo

2021-09-21 23:35 UTC, jdddog requested changes
Hey Aniek, it looks good overall, there are a few small things to fix (in the comments).

2021-09-21 23:35 UTC, jdddog commented on oaebu_workflows/dags/google_analytics_telescope.py
> -
This file doesn't need to be changed

2021-09-21 23:35 UTC, jdddog commented on oaebu_workflows/dags/oapen_irus_uk_telescope.py
> -
This file doesn't need to be changed

2021-09-21 23:35 UTC, jdddog commented on oaebu_workflows/utils/identifiers.py
> +    wos = "wos"
This file (and the whole utils sub package) isn't needed because there is already an identifiers file here: https://github.com/The-Academic-Observatory/oaebu-workflows/blob/develop/oaebu_workflows/identifiers.py

Also, scopus and wos can be removed from TelescopeTypes since they aren't a part of this package.

2021-09-23 07:09 UTC, aroelo commented
> Hey Aniek, it looks good overall, there are a few small things to fix (in the comments).

Thanks Jamie!
I just made those changes.

2021-09-23 20:53 UTC, jdddog approved these changes

2021-09-23 20:54 UTC, merged