Feature/workflow config file
The-Academic-Observatory/oaebu-workflows pull request #142
Opened 2023-03-31 06:52 UTC by keegansmith21

2023-04-25 23:47 UTC, jdddog requested changes
Hey Keegan, thanks for refactoring the code, it is looking very good. I've left some more general feedback on a couple of the workflows and tests.

2023-04-25 23:47 UTC, jdddog commented on oaebu_workflows/workflows/tests/test_elastic_workflow.py
> +                    ),
Can replace with `cloud_workspace=self.fake_cloud_workspace,`

2023-04-25 23:47 UTC, jdddog commented on oaebu_workflows/tests/test_seeding.py
> +from observatory.platform.observatory_environment import ObservatoryTestCase, find_free_port
This file can be deleted

2023-04-25 23:47 UTC, jdddog commented on oaebu_workflows/workflows/fulcrum_telescope.py
> +        oapen_irus_api_conn_id: str = "oapen_irus_uk_api",
Some general feedback for the constructors to make them consistent with what I've done so far:
* I think we can just remove `load_bigquery_table_kwargs` and `source_format` (which you've done in this one) from all of the constructors and directly set the values in the respective `bq_load_table` functions. I think that it was only really necessary with the old design.
* The table description should be none.
* The docstrings should be updated.
* It would be good to move the Airflow specific parameters to the end, e.g. `start_date`, `schedule_interval`.
* We might need to make a helper function to assert that `dag_id` is not None or an empty string and that `cloud_workspace` is not None. cloud_workspace can be None. What do you think?

2023-04-25 23:47 UTC, jdddog commented on oaebu_workflows/workflows/fulcrum_telescope.py
>          release_date = make_release_date(**kwargs).subtract(months=1)
Why is the release date the month before the execution date? As the execution date is already the start of the data interval. 

I though that it was easier to change `make_snapshot_date` to just use the `data_interval_end`. The data interval uses a semi open interval [data_interval_start, data_interval_end) where the data_interval_end is not included.

2023-04-25 23:47 UTC, jdddog commented on oaebu_workflows/workflows/fulcrum_telescope.py
>          totals_data, country_data = download_fulcrum_month_data(download_month, requestor_id)
I would probably change download_fulcrum_month_data so you pass it a pendulum date and it does the .format inside.

2023-04-25 23:47 UTC, jdddog commented on oaebu_workflows/workflows/fulcrum_telescope.py
> +        bq_load_table(
You should also check if `bq_load_table` was successful or not with set_task_state(success, self.bq_load.__name__, release)

2023-04-25 23:47 UTC, jdddog commented on oaebu_workflows/workflows/fulcrum_telescope.py
> +        self.observatory_api_conn_id = observatory_api_conn_id
The cleanup task should come after add_new_dataset_releases

2023-04-25 23:47 UTC, jdddog commented on oaebu_workflows/workflows/tests/test_fulcrum_telescope.py
> +            dag_id="fulcrum_test", cloud_workspace=cloud_workspace, publishers=FAKE_PUBLISHERS
You can replace `cloud_workspace=cloud_workspace` with `cloud_workspace=self.cloud_workspace` now for `test_dag_structure` and `test_dag_load`.

2023-04-25 23:47 UTC, jdddog commented on oaebu_workflows/workflows/tests/test_fulcrum_telescope.py
> +            self.assert_dag_load_from_config("fulcrum_test")
If there are any required keyword arguments that are specified in kwargs, it would be best to check that an AssertionError is raised:

```python
        # Failure to load caused by missing kwargs
        env = ObservatoryEnvironment(
            workflows=[
                Workflow(
                    dag_id=self.dag_id,
                    name="Scopus Telescope Curtin University",
                    class_name="academic_observatory_workflows.workflows.scopus_telescope.ScopusTelescope",
                    cloud_workspace=self.fake_cloud_workspace,
                    kwargs=dict(),
                )
            ]
        )

        with env.create():
            with self.assertRaises(AssertionError) as cm:
                self.assert_dag_load_from_config(self.dag_id)
            msg = cm.exception.args[0]
            self.assertTrue("missing 2 required keyword-only arguments" in msg)
            self.assertTrue("institution_ids" in msg)
            self.assertTrue("scopus_conn_ids" in msg)
```

2023-04-25 23:47 UTC, jdddog commented on oaebu_workflows/workflows/tests/test_fulcrum_telescope.py
>          self.host = "localhost"
You can remove all of the API environment stuff from the constructor as well as the setup_api and setup connections methods.

2023-04-25 23:47 UTC, jdddog commented on oaebu_workflows/workflows/tests/test_fulcrum_telescope.py
>          # Setup Observatory environment
Take a look at test_telescope to get an idea about what can be changed here: https://github.com/The-Academic-Observatory/academic-observatory-workflows/blob/feature/workflow-config-file/academic_observatory_workflows/workflows/tests/test_crossref_metadata_telescope.py#L105

2023-04-25 23:47 UTC, jdddog commented on oaebu_workflows/workflows/tests/test_fulcrum_telescope.py
> +                cloud_workspace=cloud_workspace,
Can replace `cloud_workspace=cloud_workspace` with `env.cloud_workspace`

2023-04-25 23:47 UTC, jdddog commented on oaebu_workflows/workflows/tests/test_fulcrum_telescope.py
> +                env.run_task(telescope.check_dependencies.__name__)
You should always test that the task state is successful, as it could be in an invalid state, e.g. skipped, or failure.

```
ti = env.run_task(telescope.check_dependencies.__name__)
self.assertEqual(State.SUCCESS, ti.state)
```

2023-04-25 23:47 UTC, jdddog commented on oaebu_workflows/workflows/tests/test_fulcrum_telescope.py
>                  self.assertEqual(len(dataset_releases), 1)
To test dataset releases and cleanup, you can generally use this snippet, when there is only 1 release:
```python
# Test that DatasetRelease is added to database
dataset_releases = get_dataset_releases(dag_id=self.dag_id, dataset_id=workflow.api_dataset_id)
self.assertEqual(len(dataset_releases), 0)
ti = env.run_task(workflow.add_new_dataset_releases.__name__)
self.assertEqual(State.SUCCESS, ti.state)
dataset_releases = get_dataset_releases(dag_id=self.dag_id, dataset_id=workflow.api_dataset_id)
self.assertEqual(len(dataset_releases), 1)

# Test that all workflow data deleted
ti = env.run_task(workflow.cleanup.__name__)
self.assertEqual(State.SUCCESS, ti.state)
self.assert_cleanup(release.workflow_folder)
````

2023-04-26 03:17 UTC, keegansmith21 commented on oaebu_workflows/dags/onix_workflow.py
>  from oaebu_workflows.workflows.onix_workflow import OnixWorkflow
OaebuPartners? This should still be required as the config file points to each partner when loading the onix workflow dag

2023-05-18 21:22 UTC, jdddog requested changes
Hey Keegan, the changes look good, I've just left a few comments. It would also be good to set the partition_date field in the API for the oaebu workflows that use partioned tables.

2023-05-18 21:22 UTC, jdddog commented on oaebu_workflows/workflows/google_analytics_telescope.py
>                      }
Does the query with the dateRanges parameter include the endDate? [data_interval_start, data_interval_end) is a half open interval, so data_interval_start <= valid dates < data_interval_end.

2023-05-18 21:22 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
>              raise AirflowException(f"Publisher ID is not set in 'extra' of telescope, extra example: {expected_extra}")
I don't think this is necessary anymore because publisher_id is specified in the constructor and the DAG won't be created if it isn't specified.

2023-05-18 21:22 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
> +            ):
Perhaps more straightforward to remove the zip and do this:
[(self.bq_country_table_name, self.bq_country_table_description, release.transform_country_path), (self.bq_institution_table_name, self.bq_institution_table_description, release.transform_institution_path)]

2023-05-18 21:22 UTC, jdddog commented on oaebu_workflows/workflows/onix_workflow.py
> +from typing import List, Optional, Tuple, Union
Nice work on simplifying the Onix Workflow!

2023-05-24 06:02 UTC, keegansmith21 commented on oaebu_workflows/workflows/onix_workflow.py
> +from typing import List, Optional, Tuple, Union
Thanks! It was definitely the most challenging part of the refactor. I think it can still be better, but it's much cleaner now :smile:

2023-05-24 06:05 UTC, keegansmith21 commented on oaebu_workflows/workflows/jstor_telescope.py
> +            ):
Oh yeah... I wonder why I'd never done it this way before. Thanks for the suggestion!

2023-05-28 20:20 UTC, jdddog approved these changes
Thanks Keegan, the changes look good.

2023-05-28 20:21 UTC, merged