Cok 531/update bad readthedocs
The-Academic-Observatory/oaebu-workflows pull request #163
Opened 2023-07-18 05:41 UTC by kathrynnapier

- Revamp of documentation to include BAD project background, updated links to template dashboard, contact info and figures.
- Removed all redundant user guides and reference to kibana/elastic.
- Incorporated rather hacky formatting to break long strings in schema tables and wrap text on a new line, to prevent long field names from overflowing into new columns when a longtable is rendered in pdf format. I did not use hyphens to avoid confusion in field names.
- html view of strings like 'Book_Visits_BV_' displays a hyperlink, and in pdf format, these are formatted in bold red text. I couldn't identify how to correct this.

Added in crossref events and metadata to the telescopes, with links to the academic observatory workflows where appropriate.

Would appreciate your review and thoughts @keegansmith21 , and I'll rebase once the PR has gone through to pull in IRUS name changes https://github.com/The-Academic-Observatory/oaebu-workflows/pull/160

2023-07-25 08:20 UTC, keegansmith21 commented on docs/bad_project/overview/how_works.md
> +The BAD project technology stack uses the book industry metadata interchange standard ONIX, combined with open bibliographic metadata (Crossref and OAPEN) to integrate usage data from multiple source
Perhaps we should also mention that it's designed to run with Apache Airflow as a manager/scheduler and in conjunction with the Observatory Platform?

2023-07-25 08:23 UTC, keegansmith21 commented on docs/bad_project/overview/partner_data.md
> +IRUS provides COUNTER standard access reports for eBooks hosted on the [OAPEN library and platform](https://oapen.org/). OAPEN "promotes and supports the transition to open access for academic books
It might be worth putting a sentence in the glossary in regards to the COUNTER standard

2023-07-25 08:39 UTC, keegansmith21 commented on docs/oaebu_workflows/telescopes/irus_fulcrum.md
> +The IRUS Fulcrum telescope collects usage statistics for titles accessed via the [Fulcrum Platform](https://www.fulcrum.org/). Usage data is accessible through [IRUS](https://irus.jisc.ac.uk/r5/) in
I think this file link should say ./irus_oapen.md

2023-07-25 09:09 UTC, keegansmith21 commented on docs/oaebu_workflows/telescopes/crossref_events.md
> +# Crossref Events
I wonder if the crossref events and metadata should be under the "telescopes" category since the table creation of both are done as part of the onix workflow? It might make more sense to put this content in the onix workflow explanation. What do you think?

2023-07-25 09:14 UTC, keegansmith21 requested changes
Thanks for making these changes Kathryn! Just a few comments for you to take a look at and it should be good to go.

2023-07-26 02:12 UTC, kathrynnapier commented on docs/oaebu_workflows/telescopes/crossref_events.md
> +# Crossref Events
I was wondering the same. But I'd like to include the schemas and the layout of the telescope files makes sense. I've added in a sentence to the crossref telescope files to explain they are created in the onix workflow stage, and link to the telescope information in the onix_workflow_step_1. What do you think?

2023-07-26 02:45 UTC, keegansmith21 approved these changes
Thanks for making these changes Kathryn! :+1:

2023-07-26 05:06 UTC, merged