Added more responsibility to data partner class
The-Academic-Observatory/oaebu-workflows pull request #187
Opened 2023-09-15 09:38 UTC by keegansmith21

2023-10-02 03:16 UTC, jdddog reviewed
Hey Keegan, here are some initial comments, I need to think a bit more about some of the changes.

2023-10-02 05:10 UTC, keegansmith21 commented on oaebu_workflows/database/sql/create_book_products.sql.jinja2
> +This will either point to 'empty_google_analytics3' (the name of this SQL block) or the name of the real data table in bigquery.
Ah the issue is that they've changed the metrics that they report on. I don't believe metrics between ga3 and 4 will be interchangeable. See [here](https://www.linkedin.com/pulse/google-analytics-ga4-vs-ga3-ellie-edwards/). It is my belief that, because the reported metrics differ, we should try to keep a healthy separation between the sources.

We don't currently have any publisher able to support ga4, which makes it difficult to determine how different it'll be when scraping; so I guess the name change is a bit preemptive in this regard.

2023-10-04 02:11 UTC, keegansmith21 commented on oaebu_workflows/oaebu_partners.py
> +    google_analytics3=OaebuPartner(
Updated to reflect this layout in recent commit

2023-10-10 04:26 UTC, jdddog requested changes
Hey Keegan, thanks for updating the schema layout, that looks good. The copyright dates still need to be updated though, e.g. where the dates have been changed from 2020 to 2023, they should instead read 2020-2023.

2023-10-10 04:28 UTC, jdddog commented on oaebu_workflows/oaebu_partners.py
> +        return partner
Perhaps this could come first

2023-10-13 05:42 UTC, jdddog approved these changes
Thanks Keegan, the changes look good.

2023-10-13 06:05 UTC, merged