initial
The-Academic-Observatory/oaebu-workflows pull request #194
Opened 2023-10-13 04:11 UTC by keegansmith21

2023-10-31 08:12 UTC, alexmassen-hane approved these changes
Thanks Keegan, looks good.

2023-11-03 04:52 UTC, jdddog requested changes
Hey Keegan, I think it is largely good to go, just some small comments.

2023-11-03 04:52 UTC, jdddog commented on oaebu_workflows/onix_utils.py
> +        with open(save_path, "w") as f:
You can remove the outer `with open(save_path, "w") as f:` and put it under `if format == "xml":`

2023-11-03 04:52 UTC, jdddog commented on oaebu_workflows/onix_utils.py
> +                xmltodict.unparse(metadata, output=f, pretty=True)
I get the warning:

```python
Unexpected type(s): (list[dict], TextIO, bool) Possible type(s): (Mapping[str, Any], SupportsWrite[bytes] | SupportsWrite[str], Any) (Mapping[str, Any], None, Any) 
```

2023-11-03 04:52 UTC, jdddog commented on oaebu_workflows/onix_utils.py
> +        filtered_metadata = filter_through_schema(self.current_metadata, schema)
The types seem incorrect here: `Expected type 'dict', got 'list[dict]' instead`

2023-11-03 04:52 UTC, jdddog commented on oaebu_workflows/onix_utils.py
> +        fixed_products = normalise_related_products(metadata["ONIXMessage"]["Product"])
I get the error: 

```python
Unexpected type(s): (str) Possible type(s): (SupportsIndex) (slice) 
```

2023-11-03 04:52 UTC, jdddog commented on oaebu_workflows/onix_utils.py
> +            related_product = {"ProductRelationCode": relation_code, "ProductIdentifier": []}
Is `relation_code` here meant to come from the item in `related_products`?

2023-11-06 05:36 UTC, keegansmith21 commented on oaebu_workflows/onix_utils.py
> +            related_product = {"ProductRelationCode": relation_code, "ProductIdentifier": []}
Ah yes good catch. In practice this makes little difference as OAPEN always gives a relation code of "06". But I've amended it with the latest commit.

2023-11-08 01:42 UTC, jdddog approved these changes
Thanks Keegan, thanks changes look good.

2023-11-08 02:12 UTC, merged