Add collections to JSTOR Telescope
The-Academic-Observatory/oaebu-workflows pull request #197
Opened 2023-10-19 06:56 UTC by keegansmith21

2023-11-03 04:30 UTC, jdddog requested changes
Thanks for the PR Keegan, it looks good. You could consolidate some of the functionality for the Publisher and Collections classes by using inheritance.

2023-11-03 04:30 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
> +class Publisher:
The Publisher and Collections classes are an example where you could use inheritance to make the code easier to manage.

You can have a top level class called `JstorAPI`, add the common functionality to it and also add interfaces for the methods that need to be implemented by `JstorCollectionsAPI` and `JstorPublishersAPI`. See at the bottom for an example of the base class.

Then instead of having if statements like this throughout the workflow, you can just have one place where you decide what class will be used (e.g. in the constructor or make_release) and then refer to the same object and and call the same methods throughout the code, without the if statements.

```python
        if self.collection:
            available_reports = Collection.list_reports(service, self.publisher_id)
        else:
            available_reports = Publisher.list_reports(service, self.publisher_id)
```


```python
class JstorAPI(ABC):
    def __init__(self, service: Any):
        self.service = service

    @retry(stop=stop_after_attempt(JstorTelescope.MAX_ATTEMPTS), reraise=True, wait=JstorTelescope.WAIT_FN)
    def get_header_info(self, url: str) -> tuple[Any, Any]:
        """Get header info from url and parse for filename and extension of file.

        :param url: Download url
        :return: Filename and file extension
        """
        logging.info(
            f"Getting HEAD of report: {url}, "
            f'attempt: {Publisher.get_header_info.retry.statistics["attempt_number"]}, '
            f'idle for: {Publisher.get_header_info.retry.statistics["idle_for"]}'
        )
        headers = {"User-Agent": get_user_agent(package_name="oaebu_workflows")}
        response = requests.head(url, allow_redirects=True, headers=headers)
        if response.status_code != 200:
            raise AirflowException(
                f"Could not get HEAD of report download url, reason: {response.reason}, "
                f"status_code: {response.status_code}"
            )
        filename, extension = response.headers["Content-Disposition"].split("=")[1].split(".")
        return filename, extension

    def get_release_date_deprecated(self, report_path: str) -> tuple[DateTime, DateTime]:
        """This function is deprecated, because the headers for the reports have changed since 2021-10-01.
        It might still be used for reports that were created before this date and have not been processed yet.
        Get the release date from the "Usage Month" column in the first row of the report.
        Also checks if the reports contains data from the same month only.

        :param report_path: The path to the JSTOR report
        :return: The start and end dates
        """
        # Load report data into list of dicts
        with open(report_path) as tsv_file:
            csv_list = list(csv.DictReader(tsv_file, delimiter="\t"))

        # get the first and last usage month
        first_usage_month = csv_list[0]["Usage Month"]
        last_usage_month = csv_list[-1]["Usage Month"]

        # check that month in first and last row are the same
        if first_usage_month != last_usage_month:
            raise AirflowException(
                f"Report contains data from more than 1 month, start month: {first_usage_month}, "
                f"end month: {last_usage_month}"
            )

        # get the release date from the last usage month
        start_date = pendulum.from_format(first_usage_month, "YYYY-MM").start_of("month").start_of("day")
        end_date = pendulum.from_format(last_usage_month, "YYYY-MM").end_of("month").start_of("day")

        return start_date, end_date

    @abstractmethod
    def list_reports(self, publisher_id: str) -> List[Dict]:
        pass

    @abstractmethod
    def get_release_date(self, report_path: str) -> tuple[DateTime, DateTime]:
        pass

    @abstractmethod
    def transform_report(self, *args, **kwargs) -> None:
        pass

```

2023-11-03 04:30 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
> +    def get_release_date(report_path: str) -> pendulum.DateTime:
The return types for many of these methods should be `tuple[pendulum.DateTime, pendulum.DateTime]`

2023-11-07 08:43 UTC, keegansmith21 commented on oaebu_workflows/workflows/jstor_telescope.py
> +class Publisher:
Thanks @jdddog , I've proceeded with this implementation. Please take a look and let me know what you think. 

I've also gone ahead and renamed a few things to be more accurate (such as *publisher_id* -> *entity_id*). The PR description has been updated to reflect these changes.

2023-11-08 01:29 UTC, jdddog requested changes
Thanks for the changes Keegan, it is looking good. Just a few smaller suggestions.

2023-11-08 01:29 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
> +            raise AirflowException(f"Entity type must be 'publisher' or 'collection', got {entity_type}.")
I would put this in a function and call it only when you need it from within the tasks, otherwise it will break the loading of all of the DAGs if someone doesn't specify the Airflow connection key.

```python
def make_jstor_api(entity_type: str, entity_id: str):
    # Create the Jstor API Instance
    service = create_gmail_service()
    if entity_type == "publisher":
        jstor_api = JstorPublishersAPI(service, entity_id)
    elif entity_type == "collection":
        jstor_api = JstorCollectionsAPI(service, entity_id)
    else:
        raise AirflowException(f"Entity type must be 'publisher' or 'collection', got {entity_type}.")

    return jstor_api
```

2023-11-08 01:29 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
>          self.add_setup_task(self.check_dependencies)
Is the re-implementation of `check_dependencies` necessary?

2023-11-08 01:29 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
> +        available_reports = self.jstor_api.list_reports()
An example of how to create the API instance.

```suggestion
        api = make_jstor_api(self.entity_type, self.entity_id)
        available_reports = api.list_reports()
```

2023-11-08 01:29 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
>                  transfrom_country=release.transform_country_path,
```suggestion
                transform_country=release.transform_country_path,
```

2023-11-08 01:29 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
> +    def transform_reports(self, *args, **kwargs) -> None:
```suggestion
    def transform_reports(
        self,
        download_country: str,
        download_institution: str,
        transform_country: str,
        transform_institution: str,
        partition_date: pendulum.DateTime,
    ) -> None:
        pass
```

2023-11-08 01:29 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
> +    def add_labels(self, report_info: List[dict]) -> bool:
```suggestion
    def add_labels(self, reports: List[dict]) -> bool:
```

2023-11-08 01:29 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
> +    def download_report(self, report: str, download_path: str) -> None:
```suggestion
    def download_report(self, report: dict, download_path: str) -> None:
```

2023-11-08 01:29 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
> +        transform_institution: str,
```suggestion
        download_country: str,
        download_institution: str,
        transform_country: str,
        transform_institution: str,
```

2023-11-08 01:29 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
> +            [download_country, transfrom_country],
```suggestion
            [download_country, transform_country],
```

2023-11-08 01:29 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
> +        :param transfrom_country: The path to write the transformed country file to
```suggestion
        :param transform_country: The path to write the transformed country file to
```

2023-11-08 01:29 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
> +    def add_labels(self, reports: List[str]) -> bool:
```suggestion
    def add_labels(self, reports: List[dict]) -> bool:
```

2023-11-08 01:29 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
> +        transfrom_country: str,
```suggestion
        download_country: str,
        download_institution: str,
        transform_country: str,
```

2023-11-08 01:29 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
> +            ["Country_Name", download_country, transfrom_country],
```suggestion
            ["Country_Name", download_country, transform_country],
```

2023-11-08 01:29 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
> +        :param transfrom_country: The path to write the transformed country file to
```suggestion
        :param transform_country: The path to write the transformed country file to
```

2023-11-08 01:29 UTC, jdddog commented on oaebu_workflows/workflows/jstor_telescope.py
> +    def add_labels(self, reports: List[str]) -> bool:
```suggestion
    def add_labels(self, reports: List[dict]) -> bool:
```

2023-11-08 05:26 UTC, keegansmith21 commented on oaebu_workflows/workflows/jstor_telescope.py
>          self.add_setup_task(self.check_dependencies)
Nope. Not sure why it was there to begin with but I'll remove it.

2023-11-08 22:33 UTC, jdddog approved these changes
Thanks for the changes Keegan

2023-11-08 22:58 UTC, merged