astro migration
The-Academic-Observatory/oaebu-workflows pull request #212
Opened 2024-01-24 05:42 UTC by keegansmith21

# Astro Migration

This PR refactors the codebase for use with The Astronomer Airflow service. Broadly speaking, the changes are as follows:
- Change DAG creation to use the Airflow Taskflow API
- Upgrade to Ariflow 2.7.3
- Removed setup.py and setup.cfg - oaebu-workflows is no longer an installable package
- Created Dockerfile, which inherits from the Astro airflow image. Used to ship to Astro deployment
- Move all workflow files (and their dependent files) into the dag folder (ready for Astro shipping)
- Move tests to the ./tests folder
- Update the API usage to the new Dataset API (https://github.com/The-Academic-Observatory/observatory-platform/pull/653) that uses BigQuery as a storage service for Release objects
- Update the workflow Release objects to be passed as Xcoms between tasks (a benefit of the taskflow upgrade)
- Collapse the upload tasks into their respective file creation tasks. i.e. upload_downloaded() is absorbed into download(). This is necessary now as we no longer necessarily have persistent disks in Astro deployments.
- Bigquery tasks create the client on behalf of their appropriate publisher, rather than have them all invoke the default environment project.
- Updated telescopes that can have multiple releases to use the new dynamic tasks functionality of the taskflow API

2024-03-04 23:38 UTC, jdddog requested changes
Hey Keegan, nice work on getting the migration done so quickly. See below for some comments on a few things that could be changed.

2024-03-04 23:38 UTC, jdddog commented on dags/oaebu_workflows/irus_fulcrum_telescope/irus_fulcrum_telescope.py
> +        bq_table_description = "Fulcrum metrics as recorded by the IRUS platform"
Could just put directly in the keyword argument?

2024-03-04 23:38 UTC, jdddog commented on dags/oaebu_workflows/irus_oapen_telescope/irus_oapen_telescope.py
> +        bq_table_description = "OAPEN metrics as recorded by the IRUS platform"
Could you put this directly in the keyword argument?

2024-03-04 23:38 UTC, jdddog commented on dags/oaebu_workflows/irus_oapen_telescope/irus_oapen_telescope.py
> +        def make_release(**context) -> List[IrusOapenRelease]:
Like Google Books, this workflow could also make use of dynamic tasks and a taskgroup for processing releases.

2024-03-04 23:38 UTC, jdddog commented on dags/oaebu_workflows/irus_oapen_telescope/irus_oapen_telescope.py
> +                set_task_state(success, context["ti"].task_id, release=release)
Maybe better to just add a check and throw a FileNotFoundException if you can't find the file.

2024-03-04 23:38 UTC, jdddog commented on dags/oaebu_workflows/jstor_telescope/jstor_telescope.py
> +        def download(available_reports: List[dict], **context) -> List[dict]:
Like Google Books, this workflow could make use of dynamic tasks and a task group to process each report.

2024-03-04 23:38 UTC, jdddog commented on dags/oaebu_workflows/onix_telescope/onix_telescope.py
> +        def make_release(**context) -> List[dict]:
Like Google Books, this workflow could make use of dynamic tasks and a task group to process each release.

2024-03-07 08:44 UTC, keegansmith21 commented on requirements.txt
>  onixcheck>=0.9.7,<1
This would have been really nice, but I'm having trouble getting it to work. I think the issue is that the oaebu dependencies are installed when the astro container is inherited. At this point, git is not installed, so pip can't pull anything using the git+https:// protocol

2024-03-07 08:57 UTC, keegansmith21 commented on dags/oaebu_workflows/irus_fulcrum_telescope/irus_fulcrum_telescope.py
> +        bq_table_description = "Fulcrum metrics as recorded by the IRUS platform"
We sure can!

2024-03-07 09:03 UTC, keegansmith21 commented on dags/oaebu_workflows/irus_oapen_telescope/irus_oapen_telescope.py
> +                set_task_state(success, context["ti"].task_id, release=release)
Sure, would you recommend something like the following:

```python
if not os.path.exists(release.download_path):
    raise FileNotFoundError(f"Could not find file: {release.download_blob_name}")
```

2024-03-07 23:15 UTC, jdddog commented on requirements.txt
>  onixcheck>=0.9.7,<1
Ah I see, that makes sense.

2024-03-07 23:16 UTC, jdddog commented on dags/oaebu_workflows/irus_oapen_telescope/irus_oapen_telescope.py
> +                set_task_state(success, context["ti"].task_id, release=release)
Yeah that would be good

2024-03-14 04:49 UTC, jdddog reviewed
Thanks for the changes Keegan, it is looking really good.

Just a few small comments.

We were settings a few parameters in the `DAG` constructor by default that differ to Airflow defaults (unless we override these in a workflow subclass).
  *  `max_active_runs` was set to 1 (Airflow pulls this from airflow.cfg if not specified) 
  * `catchup` was set to False (Airflow defaults this to True)

Could you double check that these are all set to how they were and if not, if the new default settings are OK?

We used to set `"on_failure_callback": on_failure_callback,` in default_args which creates the Slack message on failure, could we set this for each DAG?

Perhaps `retries` and `retry_delay` should be keyword argument parameters in create_dag?

2024-03-14 07:43 UTC, keegansmith21 commented
> Thanks for the changes Keegan, it is looking really good.
> 
> Just a few small comments.
> 
> We were settings a few parameters in the `DAG` constructor by default that differ to Airflow defaults (unless we override these in a workflow subclass).
> 
> * `max_active_runs` was set to 1 (Airflow pulls this from airflow.cfg if not specified)
> * `catchup` was set to False (Airflow defaults this to True)
> 
> Could you double check that these are all set to how they were and if not, if the new default settings are OK?
> 
> We used to set `"on_failure_callback": on_failure_callback,` in default_args which creates the Slack message on failure, could we set this for each DAG?
> 
> Perhaps `retries` and `retry_delay` should be keyword argument parameters in create_dag?

Hey Jamie, 

Thanks for taking another look at this PR. I've made the following changes:
- Added a max_active_runs=1 default where it was not already set
- Added the on_failure_callback from observatory platform to all dags
- Made the retries and retry_delay parameters arguments for the create_dag function with defaults set to 3 and 5 (minutes) respectively

The catchup was already set for each dag as part of the create_dag defaults.

I also found the default airlfow config args [here](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html) . But it was kind of hard to find so I much prefer explicitly stating the defaults in create_dag.

2024-03-17 21:48 UTC, jdddog approved these changes

2024-03-17 22:15 UTC, merged