OAPEN Workflow and bug fixes to ONIX workflow
The-Academic-Observatory/oaebu-workflows pull request #4
Opened 2021-08-31 02:51 UTC by rhosking

Ported pull request from observatory-platform

Adds the new OAPEN workflow, which will combine the IRUS-UK, and public metrics with the OAPEN metadata. (MEL-217 + MEL-159)

It also adds a range of fixes across the OAEBU workflows:

corrects matching for countries in google analytics (MEL-371)
changes irus-uk to use the correct country field not city locations to stop over counting (MEL-391)
adds UCL metrics for UCL press (MEL-212)
deduplication of metrics from Google Analytics, IRUS-UK, Google Books, UCL Press and JSTOR (MEL-387, MEL-386, MEL-379)
ensures that duplicate ONIX product records don't throw off the metrics (MEL-380, MEL-379)
Adds work and work_family IDs to the exported tables (where it makes sense) (MEL-385)
Adds titles to the unmatched ISBNs (MEL-384)

2021-09-02 04:59 UTC, jdddog reviewed
Hey Richard, it looks good to me overall, just a few small suggestions and questions

2021-09-02 04:59 UTC, jdddog commented on oaebu_workflows/workflows/oapen_workflow.py
> +        new_table_id = f"{table_id}{table_date.strftime('%Y%m%d')}"
This function is a duplicate of the function in onix_workflow.py module and can just be imported from there.

2021-09-02 04:59 UTC, jdddog commented on oaebu_workflows/workflows/oapen_workflow.py
> +    ORG_NAME = "OAPEN"
We've been calling it "OAPEN Press" in the API

2021-09-02 04:59 UTC, jdddog commented on oaebu_workflows/workflows/tests/test_oapen_workflow.py
> +        self.org_name = "OAPEN"
```suggestion
        self.org_name = OapenWorkflow.ORG_NAME
```

2021-09-02 04:59 UTC, jdddog commented on oaebu_workflows/workflows/oapen_workflow.py
> +        )
Why does IRUS UK need to be copied? Can't it just be queried from wherever it is?

2021-09-02 04:59 UTC, jdddog commented on oaebu_workflows/workflows/oapen_workflow.py
> +class OapenWorkflowRelease(AbstractRelease):
So that you can remove all of the unused methods, you can just not subclass AbstractRelease, it will still work. Perhaps in the type hints in the Workflow template we should let release be Any type and then the type hints will work too.

2021-09-02 05:34 UTC, rhosking commented on oaebu_workflows/workflows/oapen_workflow.py
> +        new_table_id = f"{table_id}{table_date.strftime('%Y%m%d')}"
thanks, yeah makes sense. Will change that

2021-09-02 05:34 UTC, rhosking commented on oaebu_workflows/workflows/oapen_workflow.py
> +    ORG_NAME = "OAPEN"
I don't think it is technically a press, though I will check on that. It was wondering I have been wondering what the appropriate term would be

2021-09-02 05:35 UTC, rhosking commented on oaebu_workflows/workflows/oapen_workflow.py
> +        )
yeah, that was what I wanted to do originally. I will take another look at it with fresh eyes. Essentially, by reusing the sql.jinja file from the onix workflow, it was expecting the table name and location to confirm to a particular structure. I took the approach of trying to not have to change the onix workflow as much as possible

2021-09-02 07:15 UTC, aroelo commented on oaebu_workflows/workflows/oapen_workflow.py
> +class OapenWorkflowRelease(AbstractRelease):
I think it would be better to not use the AbstractRelease class directly, I thought that the Release class was developed for this purpose, it has all the required methods/properties that you need to be able to use the Workflow class and the implemented methods.

Also, I think that all properties of the OapenWorkflowRelease (except for the release date) would probably be better in the OapenWorkflow class, as none of these are related to a specific release. They are just passed on to the release class and then extracted in the workflow class again where they are used.

2021-09-02 07:17 UTC, aroelo commented on oaebu_workflows/workflows/oapen_workflow.py
> +            ]
Are these variables required for the workflow? If so then it would be good to add the 'check_dependencies' task that is already implemented, if they are not needed this bit can probably be left out.

2021-09-02 23:40 UTC, jdddog commented on oaebu_workflows/workflows/oapen_workflow.py
> +    ORG_NAME = "OAPEN"
We are already using OAPEN Press though, so it would be better to use that for consistency

2021-09-02 23:44 UTC, jdddog commented on oaebu_workflows/workflows/oapen_workflow.py
> +class OapenWorkflowRelease(AbstractRelease):
> I think it would be better to not use the AbstractRelease class directly, I thought that the Release class was developed for this purpose, it has all the required methods/properties that you need to be able to use the Workflow class and the implemented methods.

Some of the properties and methods in the AbstractRelease and Release class aren't really needed for all types of workflows.

> Also, I think that all properties of the OapenWorkflowRelease (except for the release date) would probably be better in the OapenWorkflow class, as none of these are related to a specific release. They are just passed on to the release class and then extracted in the workflow class again where they are used.

Yeah that sounds good, also gcp_project_id should be included.

2021-09-03 01:19 UTC, jdddog requested changes

2021-09-03 01:19 UTC, jdddog commented on oaebu_workflows/workflows/oapen_workflow.py
> +class OapenWorkflowRelease(AbstractRelease):
```suggestion
class OapenWorkflowRelease:
```

2021-09-03 01:19 UTC, jdddog commented on oaebu_workflows/workflows/oapen_workflow.py
> +        pass
Can remove these

2021-09-03 01:19 UTC, jdddog commented on oaebu_workflows/workflows/oapen_workflow.py
> +    ORG_NAME = "OAPEN"
The ORG_NAME needs to be changed to "OAPEN Press" otherwise the sensor will hang forever

2021-09-03 01:21 UTC, jdddog commented
The code needs to be reformatted with Black

2021-09-03 01:36 UTC, jdddog requested changes

2021-09-03 01:36 UTC, jdddog commented on oaebu_workflows/workflows/oapen_workflow.py
> +        self.add_sensor(sensor)
There need to be two sensors that wait for the following DAGs to finish:
* oapen_irus_uk_oapen_press
* oapen_metadata

This also means that ORG_NAME needs to be changed to "OAPEN Press".

2021-09-03 03:42 UTC, rhosking commented on oaebu_workflows/workflows/oapen_workflow.py
> +        self.add_sensor(sensor)
Take a look at the updates I made, I think they are right, but sensors aren't something I have worked with much, so feedback would be useful

2021-09-08 23:07 UTC, jdddog requested changes
Hey Richard, the changes look good. I've left some comments about simplifying some of the template code.

Also, can you change black to use a line length of 120 and reformat the changed files. In PyCharm in external tools settings, change the "Arguments" field to `"$FilePath$" --line-length 120`

2021-09-08 23:07 UTC, jdddog commented on oaebu_workflows/workflows/oapen_workflow.py
> +        )
The template `create_book_products.sql.jinja2` can be simplified so that you don't need to copy the `oapen_irus_uk` dataset and also don't need to specify so many variables for the template.

In the Jinja2 template you can check if a variable is defined or not:
```jinja2
{% if variable is not defined %}
```
So instead of having the variables `google_analytics=False, google_books=False, jstor=False, oapen=True, ucl=False, onix_workflow=False` you can just check if the table_id variable is defined or not.

Then, also change the template to supply the whole table_id. We might need to change some of our terminology to be consistent with BigQuery:
* table name: jstor or jstorYYYYMMDD
* table id: project_id.dataset_id.table_name.

So instead of this:
```sql
jstor_institution_metrics as (
    SELECT
        eISBN as ISBN13, release_date, ARRAY_AGG(STRUCT(Institution, Total_Item_Requests)) as metrics
    FROM {% if jstor %} `{{ project_id }}.{{ dataset_id }}.{{ jstor_dataset }}_jstor_institution_matched{{ release_date.strftime('%Y%m%d') }}` {% else %} empty_jstor_institution {% endif %} as jstor_institution
    GROUP BY eISBN, release_date
),
```

Can do this:
```sql
jstor_institution_metrics as (
    SELECT
        eISBN as ISBN13, release_date, ARRAY_AGG(STRUCT(Institution, Total_Item_Requests)) as metrics
    FROM {% if jstor_table_id is defined  %} `{{ jstor_table_id }}` {% else %} empty_jstor_institution {% endif %} as jstor_institution
    GROUP BY eISBN, release_date
),
```

Also, some of the variables passed to the template are unused, e.g. ucl, onix_workflow, onix_workflow_dataset etc, so would be good to double check them.

2021-09-10 00:21 UTC, rhosking commented on oaebu_workflows/workflows/oapen_workflow.py
> +        )
I went a step further, and removed the logic from the jinja template, and did that in python. It was a bit of a pain using the logic for the full table_id betwen the onix and oapen workflows without doing this

2021-09-10 03:43 UTC, jdddog approved these changes

2021-09-10 03:44 UTC, merged