Mel 773/update oaebu docs
The-Academic-Observatory/oaebu-workflows pull request #70
Opened 2022-03-27 15:23 UTC by kathrynnapier

Updates to schemas, figures and workflow docs

2022-03-28 03:57 UTC, aroelo requested changes
Hi @kathrynnapier, it looks good with all the schema's added in the documentation :-)

I have added some comments/questions in the suggested file changes.

Also, for the Work ID, Work Family ID and ONIX Work ID ISBN Errors here https://oaebu-workflows--70.org.readthedocs.build/en/70/oaebu_workflows/workflows/onix_workflow_step_1.html#work-id there is no link to a query, because these tables are not created with an sql query.
Rather the data is created from python code, loaded into a gzipped jsonl file and then this file is loaded into bigquery as a table.
In this case might be useful to link to the code instead, e.g.:

```
[Link to Code](https://github.com/The-Academic-Observatory/oaebu-workflows/blob/develop/oaebu_workflows/workflows/onix_work_aggregation.py)
```

2022-03-28 03:57 UTC, aroelo commented on docs/oaebu_workflows/workflows/onix_workflow_step_1.md
> +[Link to Query](https://github.com/The-Academic-Observatory/oaebu-workflows/blob/MEL-773/update_oaebu_docs/oaebu_workflows/workflows/onix_workflow.py)
```suggestion
[Link to Query](https://github.com/The-Academic-Observatory/oaebu-workflows/blob/develop/oaebu_workflows/workflows/onix_workflow.py)
```

2022-03-28 03:57 UTC, aroelo commented on oaebu_workflows/database/schema/oaebu_public_data_country_list_2022-03-27.json
> +]
Which table does this represent? Is this an elasticsearch index for which there is no matching BigQuery table?
I can not find a country-list table in the `oaebu-public-data` GCP project.

2022-03-28 03:57 UTC, aroelo commented on oaebu_workflows/database/schema/oaebu_publisher_book_product_author_metrics_2022-03-27.json
> +[
Is the only difference with the 2021-11-25 version the added descriptions?
If that is the case I think it would be better to edit that file in place and not create a new one.

So we know that when the date in the file name has changed it resulted in actual changes in the BigQuery table.

2022-03-28 03:57 UTC, aroelo commented on oaebu_workflows/database/schema/oaebu_publisher_book_product_publisher_metrics_2022-03-27.json
> +[
Is the only difference with the 2021-11-25 version the added descriptions?
If that is the case I think it would be better to edit that file in place and not create a new one.

So we know that when the date in the file name has changed it resulted in actual changes in the BigQuery table.

2022-03-28 03:57 UTC, aroelo commented on oaebu_workflows/database/schema/oaebu_publisher_book_product_subject_year_metrics_2022-03-27.json
> +[
Is the only difference with the 2021-11-25 version the added descriptions?
If that is the case I think it would be better to edit that file in place and not create a new one.

So we know that when the date in the file name has changed it resulted in actual changes in the BigQuery table.

2022-03-28 03:57 UTC, aroelo commented on oaebu_workflows/database/schema/oaebu_publisher_book_product_year_metrics_2022-03-27.json
> +[
Is the only difference with the 2021-11-25 version the added descriptions?
If that is the case I think it would be better to edit that file in place and not create a new one.

So we know that when the date in the file name has changed it resulted in actual changes in the BigQuery table.

2022-03-28 03:57 UTC, aroelo commented on docs/oaebu_workflows/workflows/onix_workflow_step_1.md
> +```
This bit is duplicated

2022-03-28 03:57 UTC, aroelo commented on oaebu_workflows/database/schema/onix_invalid_isbn_2022-03-27.json
> +        "name": "Primary_ISBN",
```suggestion
        "name": "ISBN13",
```

The ISBN13 field is always used for the onix data source

2022-03-28 03:57 UTC, aroelo commented on oaebu_workflows/database/schema/platform_invalid_isbn_2022-03-27.json
> +]
This is a bit tricky to capture in one schema, because the "name" field is dynamic and it is different depending on the data platform.
The following names are used:
- Google Analytics: "publication_id"
- Google Books Sales: "Primary_ISBN"
- Google Books Traffic: "Primary_ISBN"
- JSTOR invalid eisbn: "eISBN" (I'm not sure why there is two tables for JSTOR with isbn/eisbn and if they're both used? There is also no separate tables for country/institution it seems)
- JSTOR invalid isbn: "ISBN"
- OAPEN IRUS UK: "ISBN"
- There is no table with invalid isbns for UCL?

2022-03-28 03:57 UTC, aroelo commented on oaebu_workflows/database/schema/platform_unmatched_isbn_2022-03-27.json
> +]
Same story as for the `oaebu_workflows/database/schema/platform_invalid_isbn_2022-03-27.json` file for the first field, the 'title' and 'release_date' fields are the same for all the different platforms.

2022-03-28 04:44 UTC, kathrynnapier commented on oaebu_workflows/database/schema/oaebu_public_data_country_list_2022-03-27.json
> +]
Jamie and I think it's been manually created- it is exported to ES as an index, and I'm hoping Jamie can update it with the new country names (wiki) included in the AO country table.

2022-03-28 04:46 UTC, kathrynnapier commented on oaebu_workflows/database/schema/oaebu_publisher_book_product_author_metrics_2022-03-27.json
> +[
Good suggestion- thanks for picking that up! Will do.

2022-03-28 04:48 UTC, kathrynnapier commented on oaebu_workflows/database/schema/platform_invalid_isbn_2022-03-27.json
> +]
Understand, do you have a suggestion for a 'generic schema', or is it better to do a new schema for all platforms?

2022-03-28 12:47 UTC, kathrynnapier commented on docs/oaebu_workflows/workflows/onix_workflow_step_1.md
> +```
Corrected, thank you

2022-03-28 12:58 UTC, kathrynnapier commented on docs/oaebu_workflows/workflows/onix_workflow_step_1.md
> +[Link to Query](https://github.com/The-Academic-Observatory/oaebu-workflows/blob/MEL-773/update_oaebu_docs/oaebu_workflows/workflows/onix_workflow.py)
Correction made, and suggested link to code also included.

2022-03-28 13:10 UTC, kathrynnapier commented on oaebu_workflows/database/schema/platform_invalid_isbn_2022-03-27.json
> +]
Added explanatory text: An example schema is below, as data platforms may use different name fields (e.g, ‘ISBN’, ‘publication_id’, ‘Primary_ISBN’).

2022-03-29 07:06 UTC, aroelo submitted a review, later dismissed
Thanks for those changes @kathrynnapier, looks good!

It just needs a rebase before merging, but besides that all good.

2022-03-30 07:00 UTC, aroelo approved these changes

2022-03-30 07:00 UTC, merged