Create .zenodo.json
The-Academic-Observatory/oaebu-workflows pull request #76
Opened 2022-03-30 02:08 UTC by jdddog

2022-03-30 02:38 UTC, aroelo commented on .zenodo.json
> +      "affiliation": "Chien",
This is the last name instead of affiliation

2022-03-30 02:38 UTC, aroelo commented on .zenodo.json
> +      "affiliation": "Quigley",
This is the last name instead of affiliation

2022-03-30 02:40 UTC, aroelo requested changes
Assuming this file was automatically created, it seems like something went wrong previously when filling in affiliations for the authors.

2022-03-30 02:43 UTC, jdddog commented on .zenodo.json
> +      "affiliation": "Chien",
Thanks Aniek

2022-03-30 02:44 UTC, jdddog commented
> Assuming this file was automatically created, it seems like something went wrong previously when filling in affiliations for the authors.

Thanks Aniek, I probably entered the info in incorrectly on Zenodo.

2022-03-30 03:11 UTC, jdddog commented
> Is it possible to change the author order for Niamh to be 3rd last instead of last? Hosking, R., Roelofs, A., Chien, T-Y., Diprose, J. P., Handcock, R. N., Ozaygen, A., Lange, R., Napier, K. R., Quigley, N., Neylon, C., & Montgomery, L. (2022). The Academic Observatory - OAeBU Workflows [Computer software].

Yep sure

2022-03-30 03:38 UTC, aroelo submitted a review, later dismissed
Thanks @jdddog, looks good.

2022-04-04 05:57 UTC, bechandcock approved these changes
That looks OK when compared to the contribution sheet, thanks.

2022-04-04 22:14 UTC, merged