INF-384: Use 2nd gen cloud function
The-Academic-Observatory/oaebu-workflows pull request #89
Opened 2022-04-21 09:17 UTC by aroelo

2022-04-26 04:04 UTC, jdddog requested changes
It looks good Aniek, I would just put a little bit of documentation in to help with understanding how to change the maximum timeout (see comment).

2022-04-26 04:04 UTC, jdddog commented on oaebu_workflows/workflows/oapen_irus_uk_telescope.py
> +            "timeoutSeconds": 900,
Is the maximum timeout 60 minutes? It would be good to define it in a constant and link to the documentation about what the true maximum is.

2022-04-26 05:53 UTC, aroelo commented on oaebu_workflows/workflows/oapen_irus_uk_telescope.py
> +            "timeoutSeconds": 900,
Yeah it is 60 minutes now, thanks for the comment. I have added some more info!

2022-04-27 01:48 UTC, jdddog approved these changes
Thanks Aniek, looks good!

2022-04-27 01:49 UTC, merged