BAD-142: Added 'page_views' to the ANU telescope metrics
The-Academic-Observatory/oaebu-workflows pull request #95
Opened 2022-06-10 07:33 UTC by keegansmith21

2022-07-01 07:12 UTC, aroelo requested changes
Great work @keegansmith21! It definitely was a bit tricky working with the Google Analytics API and inspecting at each point of the process where the numbers do or don't match up.

I just added one small comment on the google analytics BigQuery schema.

2022-07-01 07:12 UTC, aroelo commented on oaebu_workflows/database/schema/google_analytics_1900-01-01.json
> +  },
This schema is not used actively right now, because we only pull in Google Analytics data for ANU Press. But if we do update this it would probably be better to keep this file unchanged and add a completely new schema `oaebu_workflows/database/schema/google_analytics_2022-06-13.json`, similar to the `oaebu_workflows/database/schema/anu_press_google_analytics_2022-06-13.json` one.

2022-07-04 01:20 UTC, keegansmith21 commented on oaebu_workflows/database/schema/google_analytics_1900-01-01.json
> +  },
Thanks for the suggestion @aroelo, I've updated the files. I believe that the workflow will choose the latest suitable one based on the datestamps. Can you conform that this is correct?

2022-07-08 00:17 UTC, jdddog commented on oaebu_workflows/database/schema/google_analytics_1900-01-01.json
> +  },
Yeah it finds the latest schema based on the date.

2022-07-08 00:18 UTC, jdddog approved these changes
Thanks Keegan, it looks good to me!

2022-07-08 00:21 UTC, merged